"""Builds and runs the Kestra MCP server.

The tool set is generated by FastMCP from openapi/kestra.generated.json (Kestra's own OpenAPI spec,
fetched by scripts/fetch_spec.py). Everything that decides which tools are served comes from the
spec itself, so there is no hand-maintained operation list to keep in sync:

- toolsets are the spec's OpenAPI tags (Flows, Executions, KV, ...),
- read vs. write is the HTTP method, plus the few POST endpoints that only read or validate,
- OSS vs. Enterprise is Kestra's `x-kestra: {edition: ee}` operation extension.

Excluded operations are never registered, so they can't be called by name either.
"""

from __future__ import annotations

import json
import os
import re
from importlib import resources
from urllib.parse import quote

import httpx2
from dotenv import load_dotenv
from fastmcp import FastMCP
from fastmcp.server.providers.openapi.routing import MCPType
from fastmcp.utilities.openapi.models import HTTPRoute
from mcp.types import ToolAnnotations

SPEC_RESOURCE = resources.files("kestra_mcp.openapi").joinpath("kestra.generated.json")

# POST endpoints that only read, search, validate, export, or preview (e.g. validateFlows,
# exportFlowsByIds, getLatestExecutions). previewDispatchApp is excluded: it dispatches an app.
READ_POST = re.compile(r"^(get|list|search|validate|export|preview(?!Dispatch))")
# GET endpoints that act: webhook triggers start an execution (triggerExecutionByGetWebhook*).
WRITE_GET = re.compile(r"^triggerExecution")

_TRUTHY = {"1", "true", "yes", "on"}


def toolset_name(tag: str) -> str:
    """'Blueprint Tags' -> 'blueprint-tags'"""
    return tag.strip().lower().replace(" ", "-")


def is_read(route: HTTPRoute) -> bool:
    op_id = route.operation_id or ""
    if route.method in ("GET", "HEAD"):
        return not WRITE_GET.match(op_id)
    return bool(READ_POST.match(op_id))


def is_ee_only(route: HTTPRoute) -> bool:
    return (route.extensions.get("x-kestra") or {}).get("edition") == "ee"


def prepare_spec(spec: dict, tenant: str) -> dict:
    """Bake the tenant into every path so tools don't each ask for it, and patch request bodies
    that upstream declares without `content` (updateFlowsInNamespace), which FastMCP rejects.
    Those take YAML flow source, like the sibling createFlow/updateFlow endpoints."""
    paths = {}
    for path, methods in spec["paths"].items():
        tenant_scoped = "{tenant}" in path
        if tenant_scoped:
            path = path.replace("{tenant}", quote(tenant, safe=""))
        for op in methods.values():
            if not isinstance(op, dict):
                continue
            if tenant_scoped and "parameters" in op:
                op["parameters"] = [p for p in op["parameters"] if p.get("name") != "tenant"]
            body = op.get("requestBody")
            if body is not None and "content" not in body and "$ref" not in body:
                body["content"] = {"application/x-yaml": {"schema": {"type": "string"}}}
        paths[path] = methods
    return {**spec, "paths": paths}


def build_http_client() -> httpx2.AsyncClient:
    try:
        base_url = os.environ["KESTRA_URL"].strip().rstrip("/")
    except KeyError as exc:
        raise RuntimeError("Missing required environment variable KESTRA_URL, e.g. http://localhost:8080") from exc

    token = os.environ.get("KESTRA_API_TOKEN")
    username, password = os.environ.get("KESTRA_USERNAME"), os.environ.get("KESTRA_PASSWORD")
    if token:
        return httpx2.AsyncClient(base_url=base_url, headers={"Authorization": f"Bearer {token}"}, timeout=90.0)
    if username and password:
        return httpx2.AsyncClient(base_url=base_url, auth=(username, password), timeout=90.0)
    return httpx2.AsyncClient(base_url=base_url, timeout=90.0)  # Kestra without authentication


def build_server() -> FastMCP:
    load_dotenv()  # picks up .env in the current working directory, if present
    spec = json.loads(SPEC_RESOURCE.read_text())
    spec = prepare_spec(spec, os.environ.get("KESTRA_TENANT", "main"))

    edition = os.environ.get("KESTRA_EDITION", "oss").strip().lower()
    if edition not in ("oss", "ee"):
        raise RuntimeError(f"KESTRA_EDITION={edition!r} is not valid - use 'oss' or 'ee'.")
    read_only = os.environ.get("KESTRA_READ_ONLY", "").strip().lower() in _TRUTHY

    known = {toolset_name(t) for ms in spec["paths"].values() for op in ms.values()
             if isinstance(op, dict) for t in op.get("tags", [])}
    raw = os.environ.get("KESTRA_TOOLSETS", "all").strip().lower()
    toolsets = known if raw in ("", "all") else {t.strip() for t in raw.split(",") if t.strip()}
    if unknown := toolsets - known:
        raise RuntimeError(f"KESTRA_TOOLSETS has unknown toolset(s) {sorted(unknown)} - valid: {sorted(known)} or 'all'.")

    def route_map_fn(route: HTTPRoute, _default: MCPType) -> MCPType:
        if (edition == "oss" and is_ee_only(route)) or (read_only and not is_read(route)):
            return MCPType.EXCLUDE
        if not {toolset_name(t) for t in route.tags} & toolsets:
            return MCPType.EXCLUDE
        return MCPType.TOOL

    def mcp_component_fn(route: HTTPRoute, component) -> None:
        component.tags = {toolset_name(t) for t in route.tags} | {"read" if is_read(route) else "write"}
        component.annotations = ToolAnnotations(
            readOnlyHint=is_read(route),
            destructiveHint=route.method == "DELETE",
        )

    return FastMCP.from_openapi(
        openapi_spec=spec,
        client=build_http_client(),
        name="kestra",
        route_map_fn=route_map_fn,
        mcp_component_fn=mcp_component_fn,
        # Kestra's response schemas don't always match what the server returns; don't let a
        # mismatch turn a successful call into an error. Results are still structured JSON.
        validate_output=False,
    )


def main() -> None:
    build_server().run()  # stdio transport by default - Claude Code spawns this as a subprocess


if __name__ == "__main__":
    main()
